//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DocGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocGia()
        {
            this.DangKies = new HashSet<DangKy>();
            this.Muons = new HashSet<Muon>();
            this.QuaTrinhMuons = new HashSet<QuaTrinhMuon>();
        }
    
        public int ma_docgia { get; set; }
        public string ho { get; set; }
        public string tenlot { get; set; }
        public string ten { get; set; }
        [Required(ErrorMessage = "Vui lòng nh?p tài kho?n")]
        public string taikhoan { get; set; }
        [Required(ErrorMessage = "Vui lòng nh?p m?t kh?u")]
        [DataType(DataType.Password)]
        public string matkhau { get; set; }
        public string vaitro { get; set; }

        [NotMapped]
        [Compare("matkhau", ErrorMessage = "M?t kh?u không trùng kh?p!")]
        public string nhaplaimatkhau { get; set; }
        [NotMapped]
        public string loidangnhap { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKy> DangKies { get; set; }
        public virtual NguoiLon NguoiLon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Muon> Muons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhMuon> QuaTrinhMuons { get; set; }
        public virtual NguoiLon NguoiLon1 { get; set; }
    }
}
