//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuaTrinhMuon
    {
        public int isbn { get; set; }
        public short ma_cuonsach { get; set; }
        public System.DateTime ngayGio_muon { get; set; }
        public int ma_docgia { get; set; }
        public Nullable<System.DateTime> ngay_hethan { get; set; }
        public Nullable<System.DateTime> ngayGio_tra { get; set; }
        public Nullable<decimal> tien_muon { get; set; }
        public Nullable<decimal> tien_datra { get; set; }
        public Nullable<decimal> tien_datcoc { get; set; }
        public string ghichu { get; set; }
    
        public virtual CuonSach CuonSach { get; set; }
        public virtual DocGia DocGia { get; set; }
    }
}
